name = "DocExtensions"
uuid = "cbdad009-89f1-4e05-85a0-06b07b50707d"
authors = ["Samuel Omlin"]
version = "0.2.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
